# Streamlit Secrets Configuration File
OPENAI_API_KEY = "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"
API = "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"
